#!/bin/bash

if ! [ -e "/usr/bin/fuseiso" ] ; then
	echo "Please install fuseiso first"
	exit 1
fi

if ! mountpoint -q "$2"; then
	echo "$2 is not a mount point"
	exit 1
fi

echo "Clean $2"
sudo rm -rf "$2"/*
sudo rm -rf "$2"/.disk
sudo rm -rf "$2"/.oem

echo "rsync iso $1 to $2"
MNT=$(mktemp -d)
fuseiso "$1" "$MNT"

if ! mountpoint -q "$MNT"; then
	echo "$MNT is not a mount point"
	exit 1
fi

rsync -rltD --progress "$MNT/" "$2/"

echo "rsync iso $1 to $2 done, umount $MNT and $2"
fusermount -u "$MNT"
sudo umount "$2"

echo "Copy iso completed"
notify-send -u critical "Copy ISO done" "$1"
